name: flutter_image_converter
description: >-
  Ultimate converter between Dart & Flutter images: ui, widgets, package image,
  ImageProvider, raw bytes, Base64 string. Works in any direction.
repository: https://github.com/signmotion/flutter_image_converter
topics:
  - converter
  - image
  - widget
  - format
  - bytes

# Compatible with https://semver.org
# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.25.8

flutter:
  uses-material-design: true

screenshots:
  - description: "FlutterImageConverter demo"
    path: images/screenshots/1.webp
